version: '3'
services:
  db:
    container_name: sixfure-db
    image: 788210522308.dkr.ecr.us-east-1.amazonaws.com/sixfure-db:develop
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: sixfure
      MYSQL_USER: sixfure
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: '100M'
      #   reservations:
      #     cpus: '0.2'
      #     memory: '800M'

  redis:
    container_name: sixfure-redis
    image: 788210522308.dkr.ecr.us-east-1.amazonaws.com/sixfure-redis:develop
    ports:
      - "6379:6379"
    expose:
      - "6379"
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: '100M'
      #   reservations:
      #     cpus: '0.2'
      #     memory: '800M'

  ui:
    container_name: sixfure-ui
    image: 788210522308.dkr.ecr.us-east-1.amazonaws.com/sixfure-ui:develop
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: '100M'
      #   reservations:
      #     cpus: '0.2'
      #     memory: '800M'

  weather:
    container_name: sixfure-weather
    image: 788210522308.dkr.ecr.us-east-1.amazonaws.com/sixfure-weather:develop
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: '100M'
      #   reservations:
      #     cpus: '0.2'
      #     memory: '800M'

  auth:
    container_name: sixfure-auth
    image: 788210522308.dkr.ecr.us-east-1.amazonaws.com/sixfure-auth:develop
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    networks:
      - sixfure
    expose:
      - "8080"
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: '100M'
      #   reservations:
      #     cpus: '0.2'
      #     memory: '800M'

networks:
  sixfure:
    driver: overlay
volumes:
  db-data:
  redis-data:
